"""
AWS Atlas Pro - Real-World Industry Scenarios & Issues.

For each flagship service: a realistic production incident ("scenario"), the
failure mode platform teams hit in the field ("issue"), the industry-standard
remediation ("fix"), and the alerts/metrics that would have caught it early.
Written as a teaching reference — each entry doubles as an interview answer.

Served via GET /api/v1/industry-issues and /api/v1/industry-issues/{service_id}.
"""

INDUSTRY_ISSUES = [
    {
        "service_id": "ec2",
        "service_name": "EC2",
        "category": "compute",
        "scenario": "During a Black-Friday sale, a single 3-Tier app is built on one large c5.4xlarge. Traffic triples, the box pegs at 100% CPU, and every user request times out for 40 minutes.",
        "issue": "Vertical scaling on one box has a hard ceiling and a single point of failure. Teams discover the limit mid-incident instead of ahead of it.",
        "impact": "Full outage, lost revenue, burned engineering hours during peak.",
        "fix": "Run instances behind an ALB in an Auto Scaling Group with a mixed-instances policy, min/max bounds, and a target-tracking policy on CPU or request count. Use Scheduled Scaling for predictable peaks.",
        "alerts": ["CPUUtilization > 85% for 5 min", "StatusCheckFailed_Instance > 0", "Scheduled-scaling misses forecast"],
        "tags": ["compute", "scaling", "high-availability"],
    },
    {
        "service_id": "lambda",
        "service_name": "Lambda",
        "category": "compute",
        "scenario": "A payment callback function started timing out under load. Cold starts spiked to 9 seconds after a busy holiday rollout and the API gateway returned 504s to the upstream card network.",
        "issue": "Cold starts from large layers/runtimes and no reserved concurrency; downstream calls without timeout budgets pile up and saturate the account's concurrency limit.",
        "impact": "Slow callbacks, lost webhook deliveries, downstream retries amplifying load.",
        "fix": "Provisioned concurrency for latency-critical paths, separate Lambda per concern (don't bundle heavy deps), set explicit timeouts/retries, and reserve concurrency to protect core flows from noisy neighbors.",
        "alerts": ["Duration p99 > 80% of timeout", "Throttles > 0", "IteratorAge > 1 min (stream sources)"],
        "tags": ["compute", "serverless", "latency"],
    },
    {
        "service_id": "s3",
        "service_name": "S3",
        "category": "storage",
        "scenario": "A data engineer accidentally ran `aws s3 rm --recursive` on a bucket that was the only copy of the company's customer exports. The data was gone in minutes and backups didn't exist.",
        "issue": "Buckets treated as backup targets; no versioning, no lifecycle rule, and MFA-delete not enabled — the classic 'single bucket of truth' failure.",
        "impact": "Irrecoverable data loss, audit/compliance exposure, legal liability.",
        "fix": "Enable Bucket Versioning + MFA Delete, cross-region replication to a backup bucket, Object Lock (WORM) for immutable archives, and lifecycle policies that promote to Glacier. Never delete without IAM deny + preflight checks.",
        "alerts": ["DeleteObject from prod IAM role", "Bucket size drop > 20% in 1 h", "Lifecycle transition errors"],
        "tags": ["storage", "data-loss", "backup"],
    },
    {
        "service_id": "rds",
        "service_name": "RDS",
        "category": "database",
        "scenario": "A nightly ETL job grew and started running 40 minutes past its window, locking a critical table. The app team 'fixed' it by raising instance size — but the root cause was a missing index and a runaway query.",
        "issue": "Scaling the box instead of the query. No performance insights, no statement timeouts, and maintenance windows that collide with business hours.",
        "impact": "Slow page loads, blocked writes, escalating RDS spend for zero real gain.",
        "fix": "Turn on Performance Insights, add `max_execution_time`/`statement_timeout`, review slow-query logs weekly, use read replicas for reporting, and right-size before the CPU knee, not after.",
        "alerts": ["CPU > 80% sustained", "FreeableMemory < 5%", "Deadlocks > threshold", "Storage > 90%"],
        "tags": ["database", "performance", "scaling"],
    },
    {
        "service_id": "vpc",
        "service_name": "VPC",
        "category": "networking",
        "scenario": "A subnet ran out of IPs at 2am during a deploy. New EC2 instances failed to start with 'Insufficient IP addresses', and the team had no idea because nothing monitored subnet capacity.",
        "issue": "Sparse /24 subnets sized 'because we always did it that way', no IPAM, and no capacity alerting until instances fail to launch.",
        "impact": "Deploys blocked, autoscaling stalls, emergency redesign of CIDR layout under pressure.",
        "fix": "Plan CIDR blocks for 2-3x future growth, use VPC IPAM, monitor `EC2-InsufficientIP` CloudWatch metrics, and reserve space per AZ with headroom for ASG buffers.",
        "alerts": ["Subnet free IPs < 10%", "EC2-InsufficientIP-Address", "VPC flow-log reject rate > 5%"],
        "tags": ["networking", "capacity", "planning"],
    },
    {
        "service_id": "iam",
        "service_name": "IAM",
        "category": "security",
        "scenario": "A leaked access key from a developer laptop was used to spin up hundreds of bitcoin miners in 20 minutes. The key had full admin because the team 'didn't have time' for fine-grained roles.",
        "issue": "Long-lived static keys with over-privileged policies; no access analyzer, no permission boundary, no rotation.",
        "impact": "Six-figure surprise bill, breach disclosure, keys still valid while revoked one-by-one.",
        "fix": "Prefer IAM roles + instance profiles over static keys, enforce least privilege with Access Analyzer, add permission boundaries, rotate keys automatically, and enable CloudTrail + GuardDuty to detect anomalous usage.",
        "alerts": ["Root account sign-in", "CloudTrail unauthorized-action spikes", "GuardDuty CryptoCurrency/EC2 finding"],
        "tags": ["security", "identity", "compliance"],
    },
    {
        "service_id": "dynamodb",
        "service_name": "DynamoDB",
        "category": "database",
        "scenario": "A promotional campaign caused a hot partition: one popular item absorbed all reads, hit the partition's 3000 RCU ceiling, and throttled the whole table during peak checkout.",
        "issue": "A single partition key with low cardinality plus on-demand mode that can't react fast enough — the classic hot-key problem.",
        "impact": "Throttled writes, failed checkouts, spiky error rates at exactly the moment of highest demand.",
        "fix": "Use high-cardinality keys or shard hot keys with a suffix, add read/write capacity autoscaling with aggressive scale-up, enable DAX for read-heavy bursts, and add exponential backoff + retry with jitter in code.",
        "alerts": ["ThrottledRequests > 0", "ReadThrottleEvents/WriteThrottleEvents", "DAX CPU > 70%"],
        "tags": ["database", "scaling", "serverless"],
    },
    {
        "service_id": "apigateway",
        "service_name": "API Gateway",
        "category": "compute",
        "scenario": "A mobile client started hammering an endpoint with retries after a timeout bug. The gateway had no throttling configured, so the flood cascaded into the backend Lambda pool and out through the downstream ERP.",
        "issue": "No API-level throttling or quota, no client-rate limiting, and no circuit breaker — one buggy client takes down the backend.",
        "impact": "Cross-tenant outage, downstream vendor blacklist, reputational damage.",
        "fix": "Configure account/API-level throttling, per-key quotas for tenants, burst limits, caching for hot GETs, and WAF rules with rate-based ban on abusive IPs.",
        "alerts": ["4XX > 5%", "5XX > 0 with retries", "Throttled request count", "WAF blocked request spikes"],
        "tags": ["api", "rate-limiting", "resilience"],
    },
    {
        "service_id": "cloudwatch",
        "service_name": "CloudWatch",
        "category": "management",
        "scenario": "The on-call page fired at 3am for a p99 latency spike. The team spent 90 minutes digging through three accounts before realizing the metric was coming from a stale test environment nobody decommissioned.",
        "issue": "No metric/log tagging strategy, no structured logging, and alerts without routing — noise drowns the real signal.",
        "impact": "Missed real incidents, alert fatigue, slow MTTD/MTTR, burned-out on-call.",
        "fix": "Tag everything (env, team, app), use structured JSON logs, consolidate metrics into one dashboard per service with well-defined SLO burn alerts, and route pages by severity.",
        "alerts": ["SLO burn-rate > 14.4×/10× windows", "Any CloudWatch Alarm in ALARM > 30 min", "Log error-rate anomaly"],
        "tags": ["observability", "alerting", "sre"],
    },
    {
        "service_id": "alb",
        "service_name": "Application Load Balancer",
        "category": "compute",
        "scenario": "Rollout to a new version of the service passed health checks at startup but immediately started returning 500s. Users hit the bad version for 25 minutes because the target group kept the box 'healthy'.",
        "issue": "Health checks too shallow (only TCP/HTTP 200 on a liveness path), no slow-start, no canary weight shifting.",
        "impact": "Broken traffic served to real users during every deploys, silent until complaints.",
        "fix": "Use deep health checks (a ready path that exercises the DB), set slow-start for warmup, deploy via weighted target groups or CodeDeploy blue/green, and alert on target-deregistration spikes.",
        "alerts": ["UnHealthyHostCount > 0", "TargetResponseTime p99 > SLO", "5XX error rate > 1%"],
        "tags": ["load-balancing", "deployment", "resilience"],
    },
    {
        "service_id": "autoscaling",
        "service_name": "Auto Scaling",
        "category": "compute",
        "scenario": "A morning batch job scaled the fleet from 10 to 400 instances in an hour and racked up a $40k bill before anyone noticed. The group had 'desired = max' and no scale-down protection.",
        "issue": "Misconfigured min/max (desired = max), no scale-down cooldown, no budget alarm — asymmetric scaling blows cost.",
        "impact": "Runaway spend, cloud bill shock, finance intervention.",
        "fix": "Set realistic min/max, use target-tracking + predictive scaling, add instance protection, enforce budget alerts and anomaly detection, and use Spot with capacity-optimized allocation for batch.",
        "alerts": ["DesiredCapacity jump > 5× in 10 min", "Projected EC2 cost > budget", "InstancesInService drift from desired"],
        "tags": ["scaling", "cost", "autoscaling"],
    },
    {
        "service_id": "ecs",
        "service_name": "ECS",
        "category": "compute",
        "scenario": "A container kept crash-looping after an image update, but the task count never changed because ECS kept restarting the same task definition with a bad env var from a stale parameter.",
        "issue": "Config drift between secrets/env and task definitions; no rollout strategy, no rollback guard, restart storms masked as 'transient'.",
        "impact": "Flapping services, delayed feature delivery, mystery failures that survive restarts.",
        "fix": "Use ECS Service Connect/Service Discovery, secrets from Secrets Manager mounted at deploy, and rolling or blue/green deployments with a minimum healthy percent; add deployment circuit breaker for repeated failures.",
        "alerts": ["Stopped task reason spikes", "Deployment failed (circuit breaker)", "Service CPU > 80% sustained"],
        "tags": ["containers", "deployment", "config"],
    },
    {
        "service_id": "eks",
        "service_name": "EKS",
        "category": "compute",
        "scenario": "A node auto-replacement drained 30% of pods at once during a version upgrade, and the new nodes couldn't pull images because the cluster had no image cache and OCI rate limits kicked in.",
        "issue": "Node pool upgrades without PDBs and max-unavailable control; no image caching; cluster autoscaler reacting too late.",
        "impact": "Partial downtime during every upgrade, slow pod scheduling, cascading restarts.",
        "fix": "Define PodDisruptionBudgets on every workload, upgrade node groups one AZ at a time with surge, use Bottlerocket AMIs + ECR image cache (or pre-pulled snapshots), and right-size the cluster autoscaler.",
        "alerts": ["Unschedulable pods > 0", "Node NotReady duration", "Image pull errors", "PDB disruption budget violated"],
        "tags": ["kubernetes", "containers", "upgrades"],
    },
    {
        "service_id": "cloudfront",
        "service_name": "CloudFront",
        "category": "networking",
        "scenario": "A marketing email drove 100× normal traffic. The site's S3 origin had no rate limiting, CloudFront had no origin shield, and the origin bucketed into 503s while the CDN served stale cache with 200s.",
        "issue": "Origin unprotected from cache-miss storms; no origin shield, weak cache-control headers, no WAF.",
        "impact": "Origin meltdown, stale content served as 'fresh', confused caching bugs.",
        "fix": "Enable Origin Shield, set correct Cache-Control/immutable for assets, use a WAF + rate-based rule in front, and configure origin failover to a secondary origin.",
        "alerts": ["Origin error rate (5XX) > 1%", "Cache miss ratio jump", "WAF blocked request spike"],
        "tags": ["cdn", "caching", "resilience"],
    },
    {
        "service_id": "route53",
        "service_name": "Route 53",
        "category": "networking",
        "scenario": "A DNS change to flip a failover was made at 4pm; by 6pm the support inbox was full of 'site unreachable' reports. The TTL on the old record was 86400 (24h), so users cached the dead endpoint.",
        "issue": "Long TTLs on records that should be quick to flip; no health-check routing; changes made without a rollback plan.",
        "impact": "Slow failover, users stuck on dead endpoints, extended outage window.",
        "fix": "Use low TTL (60-300s) on records you may flip, Route 53 health checks + failover/failover routing policies, and test DNS propagation in a staging domain first.",
        "alerts": ["Health check status DOWN", "DNSSEC key rollover failure", "Query volume anomaly"],
        "tags": ["dns", "failover", "availability"],
    },
    {
        "service_id": "sqs",
        "service_name": "SQS",
        "category": "application",
        "scenario": "A producer wrote a retry loop with no backoff that redelivered the same message thousands of times. With no dead-letter queue, poisoned messages were retried forever and the consumer fell behind.",
        "issue": "No DLQ, no maxReceiveCount, redrive policy missing, and consumers without idempotency.",
        "impact": "Unbounded retry storms, message pile-up, downstream duplicate effects.",
        "fix": "Configure a DLQ with maxReceiveCount (3-5), exponential backoff + jitter on the consumer, idempotency keys in messages, and monitor ApproximateAgeOfOldestMessage.",
        "alerts": ["ApproximateAgeOfOldestMessage > 5 min", "DLQ depth > 0", "ReceiveCount near maxReceiveCount"],
        "tags": ["messaging", "resilience", "queueing"],
    },
    {
        "service_id": "sns",
        "service_name": "SNS",
        "category": "application",
        "scenario": "A CI pipeline published 'deploy complete' to a topic that had grown to 12 subscribers, two of which were HTTP endpoints that started failing silently. Nobody noticed notifications were dead for a week.",
        "issue": "HTTP/S subscribers without retry policies or delivery logging; fan-out growing without governance.",
        "impact": "Silent notification loss, missed deploys, undetected downstream failures.",
        "fix": "Set delivery retry policies, log delivery failures to CloudWatch, use DLQ for SNS->SQS, and keep a subscriber manifest so additions are reviewed.",
        "alerts": ["NumberOfNotificationsDelivered drop", "Delivery failure count > 0", "SQS DLQ for topic > 0"],
        "tags": ["messaging", "fanout", "notifications"],
    },
    {
        "service_id": "kinesis",
        "service_name": "Kinesis Data Streams",
        "category": "data",
        "scenario": "A shard hot partition (one device id = 90% of events) throttled writes during a firmware rollout, dropping telemetry. The team had set shard count once at launch and never resharded.",
        "issue": "Static shard count, hot keys, and no lag monitoring — the stream silently loses the exact data you need.",
        "impact": "Lost telemetry, skewed analytics, blind spots during incidents.",
        "fix": "Right-size shard count for peak with headroom, use adaptive shard splitting, monitor GetRecords.IteratorAgeMilliseconds per shard, and fall back to S3 for the long tail.",
        "alerts": ["IteratorAgeMilliseconds > 60 s", "WriteProvisionedThroughputExceeded", "Per-shard throttling"],
        "tags": ["streaming", "data", "scaling"],
    },
    {
        "service_id": "redshift",
        "service_name": "Redshift",
        "category": "data",
        "scenario": "Dashboards slowed to a crawl during month-end reporting. The warehouse was on a single node class with no WLM, so one analyst's ad-hoc query starved the entire BI team.",
        "issue": "No workload management, sort/compression keys guessed once, no concurrency scaling, no vacuum/analyze.",
        "impact": "Slow dashboards, analyst frustration, warehouse consolidation projects triggered.",
        "fix": "Enable concurrency scaling, define WLM queues for BI vs ETL, design sort keys on common filters and distribution on join columns, and schedule VACUUM/ANALYZE on a maintenance window.",
        "alerts": ["WLM queue wait > threshold", "Concurrency scaling events", "Skew ratio > 4"],
        "tags": ["data-warehouse", "performance", "analytics"],
    },
    {
        "service_id": "glue",
        "service_name": "Glue",
        "category": "data",
        "scenario": "A nightly ETL job that worked for months suddenly failed every run after a source schema changed (a column was renamed). The job used position-based extraction and had no schema drift handling.",
        "issue": "Brittle ETL with hard-coded schemas, no schema registry, no job bookmark checks, silent reprocessing.",
        "impact": "Blocked daily pipelines, data quality issues, late reports.",
        "fix": "Use Glue Data Catalog with schema evolution, enable job bookmarks for incremental loads, add `enableSchemaEvolution`/resilience to schema changes, and alert on job state and DPU usage.",
        "alerts": ["Job FAILED/STOPPED", "DataQuality run fail", "DPU-hours > budget"],
        "tags": ["etl", "data", "schema"],
    },
    {
        "service_id": "athena",
        "service_name": "Athena",
        "category": "data",
        "scenario": "A BI team's monthly query suddenly cost $1,400 instead of $40. The data team had appended a raw CSV 'temp' partition that was never compressed or partitioned, so Athena scanned the whole thing every time.",
        "issue": "Query cost scales with bytes scanned; unpartitioned/plain-CSV tables, no compression, no cost guardrails.",
        "impact": "Bill shock on every ad-hoc query, data teams afraid to query.",
        "fix": "Partition by date/region, store Parquet/ORC with compression, use columnar projections + workgroup data-usage limits, and set cost controls at the workgroup level.",
        "alerts": ["Workgroup data-scanned > budget", "Query failed > threshold", "BytesScanned per query anomaly"],
        "tags": ["analytics", "cost", "serverless"],
    },
    {
        "service_id": "sagemaker",
        "service_name": "SageMaker",
        "category": "ml",
        "scenario": "A model retrained nightly drifted silently — churn predictions looked fine in the dashboard but the business saw response rates drop for two weeks before anyone noticed the data drift.",
        "issue": "Training and serving drift detection missing; no lineage, no version pinning, no rollback to a known-good model.",
        "impact": "Silent model degradation, wrong business decisions, no audit trail.",
        "fix": "Use SageMaker Model Monitor for data/drift alerts, store model lineage in Model Registry with approval gates, shadow-deploy canaries, and automate rollback on guardrail failure.",
        "alerts": ["DataQuality baseline drift", "Model quality metric drop", "Inference latency p99 > SLO"],
        "tags": ["ml", "maturity", "governance"],
    },
    {
        "service_id": "bedrock",
        "service_name": "Bedrock",
        "category": "ml",
        "scenario": "A support chatbot started quoting outdated product prices after the catalog updated. Users were told wrong prices for two days; the RAG knowledge base had no refresh schedule and no provenance on sources.",
        "issue": "Stale knowledge bases, no content freshness checks, no guardrails on generated output, no eval harness.",
        "impact": "Wrong answers at scale, brand damage, no way to prove what the model said or why.",
        "fix": "Schedule KB syncs, add guardrails + topic bans, log every query with trace + source citations, and run an eval harness (golden set) before every KB update.",
        "alerts": ["KB sync failure", "Guardrail intervention rate spike", "Hallucination/refusal eval score drop"],
        "tags": ["genai", "rag", "governance"],
    },
    {
        "service_id": "stepfunctions",
        "service_name": "Step Functions",
        "category": "application",
        "scenario": "An order orchestration workflow hit a transient DB error at step 7 of 12, and the whole execution failed. The retried run double-charged the customer because the payment step wasn't idempotent.",
        "issue": "Workflows without retry/catch policies on steps, no idempotency, no execution history retention policy, no SLA monitoring.",
        "impact": "Duplicate charges, stuck orders, hard-to-audit failures.",
        "fix": "Attach retry with jittered backoff per state, catch and route failures to a compensation step, enforce idempotency keys, and monitor execution failures + run time per state.",
        "alerts": ["ExecutionFailed rate > 0", "State retries > N", "Execution duration p99 > SLA"],
        "tags": ["workflow", "orchestration", "reliability"],
    },
    {
        "service_id": "secretsmanager",
        "service_name": "Secrets Manager",
        "category": "security",
        "scenario": "A DB password rotated automatically, but a batch job still used a 6-month-old cached copy. The job failed silently for a day until an alert surfaced 500 errors — secrets rotated without downstream consumers knowing.",
        "issue": "Rotated secrets cached in apps, no rotation-to-consumer sync, secrets committed to git history, no access audit.",
        "impact": "Silent auth failures, hard-to-diagnose outages, leaked credentials in repos.",
        "fix": "Store secrets only in Secrets Manager, rotate on schedule with Lambda, have apps fetch at startup + on 401 (not cache forever), scan git history for leaked keys, and enable CloudTrail for secret access.",
        "alerts": ["Secret rotation failure", "AccessDenied on secret fetch", "Secret fetched from new principal (unusual)"],
        "tags": ["security", "secrets", "rotation"],
    },
    {
        "service_id": "cognito",
        "service_name": "Cognito",
        "category": "security",
        "scenario": "A growth campaign spiked signups 50×. The user pool's default limits throttled the sign-in API, new users got 'too many requests', and the login page looked broken to every new customer for hours.",
        "issue": "Default (unscalable) user-pool limits, no adaptive auth, no MFA policy, no rate-limit planning for spikes.",
        "impact": "Lost signups at the exact moment of peak acquisition, support flood.",
        "fix": "Pre-warm the pool before campaigns, raise account limits proactively, enable adaptive authentication, add WAF rate rules on the sign-in path, and monitor sign-in failures vs successes.",
        "alerts": ["Sign-up/sign-in throttling errors", "Failed auth attempts > baseline", "Cognito internal errors"],
        "tags": ["identity", "auth", "scaling"],
    },
    {
        "service_id": "eventbridge",
        "service_name": "EventBridge",
        "category": "application",
        "scenario": "An 'order.created' event was being consumed by two teams. One team's subscriber threw an unhandled exception and silently stopped processing for a week — no one noticed because EventBridge drops failed invocations by default.",
        "issue": "No retry policy or DLQ on targets, unmonitored invocations, schema evolution breaking consumers.",
        "impact": "Silent data loss, divergent systems, uncoordinated consumers.",
        "fix": "Set target retry policy + DLQ, monitor InvocationFailureCount per rule, use schemas to version events, and test consumers against the schema registry before deploy.",
        "alerts": ["Rule InvocationFailureCount > 0", "DLQ depth > 0", "Schema registry incompatible change"],
        "tags": ["events", "decoupling", "reliability"],
    },
    {
        "service_id": "iot",
        "service_name": "IoT Core",
        "category": "messaging",
        "scenario": "A firmware rollout pushed bad configuration to 40,000 devices. Every device tried to reconnect at once, the MQTT broker flooded, and the fleet went offline for hours while support calls poured in.",
        "issue": "No fleet-level deployment strategy: unauthenticated reconnects, no shadow throttling, certificates shared across devices.",
        "impact": "Fleet-wide outage, stale telemetry, costly field support.",
        "fix": "Use per-device certificates, OTA via IoT Jobs (not raw shadows), device shadows with rate limits, and a reconnect backoff policy. Monitor connection count and messages per device.",
        "alerts": ["Connection attempt spikes", "Disconnect rate > baseline", "Device shadow update failures"],
        "tags": ["iot", "fleet", "ota"],
    },
    {
        "service_id": "connect",
        "service_name": "Connect",
        "category": "messaging",
        "scenario": "A bank's IVR hit its concurrent-calls limit during a system outage when call volume tripled. Callers got a busy signal instead of a queue, so the 'fail-safe' contact center failed exactly when it was needed.",
        "issue": "Default concurrency limits never raised, no overflow to voicemail/secondary routing, no call-volume alerting.",
        "impact": "Customers abandoned, SLA breaches, reputational hit during incidents.",
        "fix": "Pre-provision capacity for peak, route overflow to a secondary queue/voicemail, use Contact Lens to catch 'can't reach support' sentiment spikes, and alert on concurrent calls near the limit.",
        "alerts": ["Concurrent calls > 80% of limit", "Abandon rate > 10%", "Average queue wait > target"],
        "tags": ["contact-center", "capacity", "ivr"],
    },
    {
        "service_id": "detective",
        "service_name": "Detective",
        "category": "security",
        "scenario": "GuardDuty flagged a compromised role. The SOC team spent 6 hours chasing CloudTrail exports across three accounts before finally finding the API call that triggered the takeover — the blast radius was never visible.",
        "issue": "Findings without investigation tooling: no graph of related entities, no timeline, evidence scattered across raw logs.",
        "impact": "Slow MTTR, attacker time-to-exfiltrate, incomplete forensics.",
        "fix": "Enable Detective before incidents (it ingests ~2 weeks of history), link it to GuardDuty + Security Hub, and walk findings through the entity graph to trace source → impact in minutes.",
        "alerts": ["New high-severity GuardDuty finding", "Detective graph data source issues", "Investigation started/finished"],
        "tags": ["security", "forensics", "mttr"],
    },
]

# Category-level common failure modes — the 'industry standard' pitfalls per pillar.
CATEGORY_ISSUES = [
    {
        "category": "compute",
        "pillar": "Reliability",
        "issues": [
            {"title": "Single-instance everything", "detail": "One box, one AZ, no ASG. The #1 cause of preventable outages in SMBs."},
            {"title": "Scaling the box, not the query/code", "detail": "Vertical upgrade masks root cause and doubles the bill."},
            {"title": "No rollback path", "detail": "Bad deploy = manual revert under pressure. Automate blue/green or weighted routing."},
        ],
    },
    {
        "category": "database",
        "pillar": "Performance",
        "issues": [
            {"title": "Missing indexes discovered in prod", "detail": "Slow queries hit exactly when traffic grows. Use Performance Insights from day one."},
            {"title": "Hot partitions/keys", "detail": "Low-cardinality keys cause throttling at peak. Design keys for distribution, not convenience."},
            {"title": "Backups that were never restored", "detail": "A backup that has never been tested is not a backup. Restore-drill quarterly."},
        ],
    },
    {
        "category": "storage",
        "pillar": "Data Protection",
        "issues": [
            {"title": "No versioning / no WORM", "detail": "Accidental deletes are irreversible. Enable versioning + MFA delete + Object Lock."},
            {"title": "Single copy of truth", "detail": "One bucket, one region, no replication. Add CRR and test the failover."},
        ],
    },
    {
        "category": "networking",
        "pillar": "Connectivity",
        "issues": [
            {"title": "Subnet IP exhaustion", "detail": "Subnets sized for launch-day, never grown. Use IPAM and monitor free IPs."},
            {"title": "DNS TTLs too long", "detail": "Failover can't happen if clients cache 24h. Keep flip-able records at 60-300s."},
        ],
    },
    {
        "category": "security",
        "pillar": "Security",
        "issues": [
            {"title": "Static keys with admin", "detail": "Leaked key = full account compromise. Prefer roles, rotate, add permission boundaries."},
            {"title": "Secrets in git", "detail": "Committed secrets survive repo deletion. Scan history, rotate immediately."},
            {"title": "No MFA on root", "detail": "Root is the crown jewels. Hardware MFA + CloudTrail on root usage."},
        ],
    },
    {
        "category": "management",
        "pillar": "Operational Excellence",
        "issues": [
            {"title": "Alerts without routing", "detail": "Noise is the real incident. Tag resources, route by severity, page only for actionable."},
            {"title": "No SLOs", "detail": "You can't manage what you don't measure. Define burn-rate alerts per critical path."},
        ],
    },
    {
        "category": "data",
        "pillar": "Analytics",
        "issues": [
            {"title": "Cost scales with scans", "detail": "Plain CSV tables blow Athena/Redshift bills. Partition + Parquet + workgroup limits."},
            {"title": "Schema drift breaks ETL", "detail": "Position-based jobs break silently. Use catalogs, bookmarks, and drift tests."},
        ],
    },
    {
        "category": "ml",
        "pillar": "ML/AI Governance",
        "issues": [
            {"title": "Silent drift", "detail": "Models decay without alerts. Monitor data/model quality continuously."},
            {"title": "No eval before release", "detail": "Ship the prompt, skip the golden set, regret it in prod. Eval-first or don't deploy."},
        ],
    },
]

ALL_SERVICE_IDS = {issue["service_id"] for issue in INDUSTRY_ISSUES}


def get_all() -> dict:
    """Full payload for GET /api/v1/industry-issues."""
    return {
        "count": len(INDUSTRY_ISSUES),
        "services": INDUSTRY_ISSUES,
        "categories": CATEGORY_ISSUES,
    }


def get_by_service(service_id: str):
    """One service's entry, or None."""
    for issue in INDUSTRY_ISSUES:
        if issue["service_id"] == service_id:
            return issue
    return None
